-- 1. Tabel Users
CREATE TABLE IF NOT EXISTS users (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    nama VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'User',
    saldo BIGINT DEFAULT 1000000,
    password VARCHAR(255) NOT NULL DEFAULT '12345',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabel Jadwal
CREATE TABLE IF NOT EXISTS jadwal (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kereta VARCHAR(255) NOT NULL,
    rute VARCHAR(255) NOT NULL,
    kelas VARCHAR(100) NOT NULL,
    harga BIGINT NOT NULL,
    sisa_kursi INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabel Bookings
CREATE TABLE IF NOT EXISTS bookings (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    kode VARCHAR(100) UNIQUE NOT NULL,
    kereta VARCHAR(255) NOT NULL,
    rute VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Lunas',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Seed Data (Data Awal)
INSERT INTO users (username, nama, role, saldo, password) VALUES
('admin', 'Administrator', 'Admin', 1000000, 'admin123'),
('dion', 'Dion Pratama', 'User', 500000, '12345'),
('budi', 'Budi Santoso', 'User', 50000, '12345'),
('user1', 'User Satu', 'User', 500000, '12345'),
('admin1', 'Admin Satu', 'Admin', 1000000, 'admin123')
ON CONFLICT (username) DO NOTHING;

INSERT INTO jadwal (kereta, rute, kelas, harga, sisa_kursi) VALUES
('Argo Bromo Anggrek', 'Jakarta - Surabaya', 'Eksekutif', 450000, 50),
('Gajayana', 'Jakarta - Malang', 'Eksekutif', 500000, 40),
('Jayakarta', 'Jakarta - Surabaya', 'Ekonomi', 250000, 80),
('Kertajaya', 'Jakarta - Surabaya', 'Ekonomi', 200000, 120),
('Taksaka', 'Jakarta - Yogyakarta', 'Eksekutif', 380000, 60);

INSERT INTO bookings (username, kode, kereta, rute, status) VALUES
('dion', 'TRAIN-89312', 'Argo Bromo Anggrek', 'Jakarta - Surabaya', 'Lunas'),
('budi', 'TRAIN-12489', 'Jayakarta', 'Jakarta - Surabaya', 'Lunas');

-- Disable Row Level Security (RLS) agar client bisa melakukan pembacaan/penulisan data
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE jadwal DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
